export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_OUT = 'SIGN_OUT';
export const INVOICE_FETCH_SUCCESS = 'INVOICE_FETCH_SUCCESS';
export const CUSTOMERS_FETCH_SUCCESS = 'CUSTOMERS_FETCH_SUCCESS';
export const SERVICES_FETCH_SUCCESS = 'SERVICES_FETCH_SUCCESS';
